apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: microservice
build:
  artifacts:
  - image: razmjo/angular
    context: angular
    docker:
      dockerfile: Dockerfile
  - image: razmjo/frontend
    context: frontend
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/angular-depl.yaml
    - k8s/ingress.yaml
    - k8s/react-depl.yaml
