apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservice
  labels:
    name: microservice
spec:
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: "/admin"
        backend:
          service:
            name: angular-service
            port: 
              number: 80
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: react-service
            port: 
              number: 80
